# -*- coding: utf-8 -*-
"""STAT 201 Section 1.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eNvH3U2-dRL_53I-vZs8JUO5hLqVbe5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Section 1.3 Examples
temp = np.array([87, 80, 91, 60, 91, 77, 87, 77, 80, 78, 89])

# Boxplot for temp
plt.boxplot(temp)
plt.show()

# Quantiles for temp
quantiles = np.quantile(temp, [0, 0.25, 0.5, 0.75, 1])
print("Quantiles:", quantiles)


# Reading the Old Faithful data
OldFaithful = pd.read_csv("https://byu.box.com/shared/static/dksdhc8xfo58vecif6jk5jki0fhnbt5o.csv")

# View first few rows of OldFaithful
print(OldFaithful.head())

# Histogram for 'Duration' column with 5 bins
plt.hist(OldFaithful['Duration'], bins=5, color='blue')
plt.show()

# Histogram for 'Duration' column with 10 bins
plt.hist(OldFaithful['Duration'], bins=10, color='blue')
plt.show()

# Histogram for 'Duration' column with 50 bins
plt.hist(OldFaithful['Duration'], bins=50, color='blue')
plt.show()